general {
    lock_cmd = quickshell ipc call lock trigger || hyprlock
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch dpms on
}

# Screenlock
listener {
    # HYPRLOCK TIMEOUT
    timeout = 600
    on-timeout = quickshell ipc call lock trigger
}

# dpms
listener {
    # DPMS TIMEOUT
    timeout = 900
    # DPMS ONTIMEOUT
    on-timeout = hyprctl dispatch dpms off
    # DPMS ONRESUME
    on-resume = hyprctl dispatch dpms on
}

# Suspend
listener {
    # SUSPEND TIMEOUT
    timeout = 1800
}
